version: 2.1

commands:
  print_pipeline_id:
    description: "Prints the ID of the pipeline that is currently running"
    parameters:
      to:
        type: string
        default: "No pipeline parsed"
    steps:
      - run: echo << parameters.to >>

jobs:
  test-command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID 

workflows:
  my_workflow:
    jobs:
      - test-command